class CellType {
  final String id;
  final String name;
  final String scientificName;
  final double doublingTimeHours;
  final String medium;
  final List<String> acceptableMediums;
  final String description;
  final String category;
  final double optimalTemp;
  final double optimalPH;
  final double co2Percent;

  const CellType({
    required this.id,
    required this.name,
    required this.scientificName,
    required this.doublingTimeHours,
    required this.medium,
    required this.acceptableMediums,
    required this.description,
    required this.category,
    this.optimalTemp = 37.0,
    this.optimalPH = 7.4,
    this.co2Percent = 5.0,
  });
}

class CellDatabase {
  static const List<CellType> cells = [

    // ══════════════════════════════════════════
    // 줄기세포 (Stem Cells)
    // ══════════════════════════════════════════
    CellType(
      id: 'ipsc',
      name: 'iPSC',
      scientificName: 'Induced Pluripotent Stem Cell',
      doublingTimeHours: 36.0,
      medium: 'mTeSR1',
      acceptableMediums: ['mTeSR1', 'Essential 8', 'StemFlex'],
      description: '역분화 만능줄기세포. 첨단 재생의학 연구의 핵심.',
      category: '줄기세포',
    ),
    CellType(
      id: 'hesc',
      name: 'hESC',
      scientificName: 'Human Embryonic Stem Cell',
      doublingTimeHours: 30.0,
      medium: 'mTeSR1',
      acceptableMediums: ['mTeSR1', 'Essential 8', 'StemFlex'],
      description: '인간 배아줄기세포. 분화 연구에 사용.',
      category: '줄기세포',
    ),
    CellType(
      id: 'hmscs_bm',
      name: 'hMSC-BM',
      scientificName: 'Human Bone Marrow MSC',
      doublingTimeHours: 40.0,
      medium: 'MesenCult-ACF Plus',
      acceptableMediums: ['MesenCult-ACF Plus', 'α-MEM + 10% FBS', 'DMEM-LG + 10% FBS'],
      description: '골수 유래 중간엽 줄기세포. 재생의학 핵심 세포.',
      category: '줄기세포',
    ),
    CellType(
      id: 'hmscs_at',
      name: 'hMSC-AT',
      scientificName: 'Human Adipose-derived MSC',
      doublingTimeHours: 38.0,
      medium: 'MesenCult-ACF Plus',
      acceptableMediums: ['MesenCult-ACF Plus', 'α-MEM + 10% FBS', 'DMEM-LG + 10% FBS'],
      description: '지방 유래 중간엽 줄기세포. 풍부한 공급원.',
      category: '줄기세포',
    ),
    CellType(
      id: 'hmscs_uc',
      name: 'hMSC-UC',
      scientificName: 'Human Umbilical Cord MSC',
      doublingTimeHours: 36.0,
      medium: 'MesenCult-ACF Plus',
      acceptableMediums: ['MesenCult-ACF Plus', 'α-MEM + 10% FBS'],
      description: '제대혈 유래 중간엽 줄기세포.',
      category: '줄기세포',
    ),
    CellType(
      id: 'hnscs',
      name: 'hNSC',
      scientificName: 'Human Neural Stem Cell',
      doublingTimeHours: 48.0,
      medium: 'NeuroCult NS-A Basal + EGF/bFGF',
      acceptableMediums: ['NeuroCult NS-A Basal + EGF/bFGF', 'DMEM/F12 + B27 + EGF/bFGF'],
      description: '인간 신경줄기세포. 신경 재생 연구.',
      category: '줄기세포',
    ),
    CellType(
      id: 'hpsc',
      name: 'hPSC-CM',
      scientificName: 'Human PSC-derived Cardiomyocyte',
      doublingTimeHours: 72.0,
      medium: 'RPMI-1640 + B27 (insulin-free)',
      acceptableMediums: ['RPMI-1640 + B27 (insulin-free)', 'RPMI-1640 + B27'],
      description: 'iPSC 유래 심근세포. 심장 재생 연구.',
      category: '줄기세포',
    ),
    CellType(
      id: 'hpsc_hep',
      name: 'iPSC-Hep',
      scientificName: 'iPSC-derived Hepatocyte',
      doublingTimeHours: 60.0,
      medium: 'HepatoZYME-SFM',
      acceptableMediums: ['HepatoZYME-SFM', 'William\'s E + ITS'],
      description: 'iPSC 유래 간세포. 약물 대사 연구.',
      category: '줄기세포',
    ),

    // ══════════════════════════════════════════
    // 암세포주 (Cancer Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'hela',
      name: 'HeLa',
      scientificName: 'Homo sapiens Cervical Carcinoma',
      doublingTimeHours: 24.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'DMEM + 5% FBS'],
      description: '자궁경부암 유래. 가장 널리 사용되는 세포주.',
      category: '암세포주',
    ),
    CellType(
      id: 'mcf7',
      name: 'MCF-7',
      scientificName: 'Homo sapiens Breast Adenocarcinoma',
      doublingTimeHours: 29.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'RPMI-1640 + 10% FBS'],
      description: '유방암 유래. 에스트로겐 수용체 양성.',
      category: '암세포주',
    ),
    CellType(
      id: 'a549',
      name: 'A549',
      scientificName: 'Homo sapiens Lung Carcinoma',
      doublingTimeHours: 22.0,
      medium: 'DMEM/F12 + 10% FBS',
      acceptableMediums: ['DMEM/F12 + 10% FBS', 'DMEM + 10% FBS'],
      description: '폐암 유래. 호흡기 연구에 활용.',
      category: '암세포주',
    ),
    CellType(
      id: 'hct116',
      name: 'HCT116',
      scientificName: 'Homo sapiens Colorectal Carcinoma',
      doublingTimeHours: 20.0,
      medium: 'McCoy\'s 5A + 10% FBS',
      acceptableMediums: ['McCoy\'s 5A + 10% FBS'],
      description: '대장암 유래. 항암제 연구에 사용.',
      category: '암세포주',
    ),
    CellType(
      id: 'u87',
      name: 'U-87 MG',
      scientificName: 'Homo sapiens Glioblastoma',
      doublingTimeHours: 40.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'MEM + 10% FBS'],
      description: '교모세포종 유래. 뇌종양 연구에 사용.',
      category: '암세포주',
    ),
    CellType(
      id: 'pc3',
      name: 'PC-3',
      scientificName: 'Homo sapiens Prostate Carcinoma',
      doublingTimeHours: 33.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS', 'Ham\'s F-12 + 10% FBS'],
      description: '전립선암 유래. 침윤성 연구.',
      category: '암세포주',
    ),
    CellType(
      id: 'skov3',
      name: 'SKOV-3',
      scientificName: 'Homo sapiens Ovarian Carcinoma',
      doublingTimeHours: 48.0,
      medium: 'McCoy\'s 5A + 10% FBS',
      acceptableMediums: ['McCoy\'s 5A + 10% FBS'],
      description: '난소암 유래.',
      category: '암세포주',
    ),
    CellType(
      id: 'ht29',
      name: 'HT-29',
      scientificName: 'Homo sapiens Colorectal Adenocarcinoma',
      doublingTimeHours: 40.0,
      medium: 'McCoy\'s 5A + 10% FBS',
      acceptableMediums: ['McCoy\'s 5A + 10% FBS', 'DMEM + 10% FBS'],
      description: '대장선암 유래. 분화 연구에 사용.',
      category: '암세포주',
    ),
    CellType(
      id: 'panc1',
      name: 'PANC-1',
      scientificName: 'Homo sapiens Pancreatic Carcinoma',
      doublingTimeHours: 52.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '췌장암 유래.',
      category: '암세포주',
    ),
    CellType(
      id: 'du145',
      name: 'DU145',
      scientificName: 'Homo sapiens Prostate Carcinoma',
      doublingTimeHours: 34.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS', 'MEM + 10% FBS'],
      description: '전립선암 유래.',
      category: '암세포주',
    ),
    CellType(
      id: 'lncap',
      name: 'LNCaP',
      scientificName: 'Homo sapiens Prostate Carcinoma',
      doublingTimeHours: 60.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '전립선암 세포주. 안드로겐 민감성.',
      category: '암세포주',
    ),
    CellType(
      id: 't47d',
      name: 'T-47D',
      scientificName: 'Homo sapiens Breast Ductal Carcinoma',
      doublingTimeHours: 48.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '유방 도관암 세포주.',
      category: '암세포주',
    ),
    CellType(
      id: 'ht1080',
      name: 'HT-1080',
      scientificName: 'Homo sapiens Fibrosarcoma',
      doublingTimeHours: 20.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'MEM + 10% FBS'],
      description: '섬유육종 세포주. 세포 침윤 연구.',
      category: '암세포주',
    ),
    CellType(
      id: 'capan1',
      name: 'Capan-1',
      scientificName: 'Homo sapiens Pancreatic Adenocarcinoma',
      doublingTimeHours: 64.0,
      medium: 'IMDM + 20% FBS',
      acceptableMediums: ['IMDM + 20% FBS'],
      description: '췌장 선암 세포주.',
      category: '암세포주',
    ),
    CellType(
      id: 'skbr3',
      name: 'SK-BR-3',
      scientificName: 'Homo sapiens Breast Adenocarcinoma',
      doublingTimeHours: 32.0,
      medium: 'McCoy\'s 5A + 10% FBS',
      acceptableMediums: ['McCoy\'s 5A + 10% FBS', 'DMEM + 10% FBS'],
      description: '유방암 세포주. HER2 과발현.',
      category: '암세포주',
    ),
    CellType(
      id: 'mdamb231',
      name: 'MDA-MB-231',
      scientificName: 'Homo sapiens Breast Adenocarcinoma',
      doublingTimeHours: 28.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'L-15 + 10% FBS'],
      description: '삼중음성 유방암 세포주. 전이 연구.',
      category: '암세포주',
    ),
    CellType(
      id: 'sw480',
      name: 'SW480',
      scientificName: 'Homo sapiens Colorectal Adenocarcinoma',
      doublingTimeHours: 24.0,
      medium: 'L-15 + 10% FBS',
      acceptableMediums: ['L-15 + 10% FBS', 'DMEM + 10% FBS'],
      description: '대장암 세포주. KRAS 돌연변이.',
      category: '암세포주',
      co2Percent: 0.0,
    ),
    CellType(
      id: 'caco2',
      name: 'Caco-2',
      scientificName: 'Homo sapiens Colorectal Adenocarcinoma',
      doublingTimeHours: 48.0,
      medium: 'DMEM + 20% FBS',
      acceptableMediums: ['DMEM + 20% FBS'],
      description: '장 상피 모델. 경구 흡수 연구.',
      category: '암세포주',
    ),
    CellType(
      id: 'ags',
      name: 'AGS',
      scientificName: 'Homo sapiens Gastric Adenocarcinoma',
      doublingTimeHours: 32.0,
      medium: 'Ham\'s F-12 + 10% FBS',
      acceptableMediums: ['Ham\'s F-12 + 10% FBS', 'RPMI-1640 + 10% FBS'],
      description: '위선암 세포주. H. pylori 연구.',
      category: '암세포주',
    ),
    CellType(
      id: 'u2os',
      name: 'U-2 OS',
      scientificName: 'Homo sapiens Osteosarcoma',
      doublingTimeHours: 30.0,
      medium: 'McCoy\'s 5A + 10% FBS',
      acceptableMediums: ['McCoy\'s 5A + 10% FBS', 'DMEM + 10% FBS'],
      description: '골육종 세포주. DNA 손상 반응 연구.',
      category: '암세포주',
    ),

    // ══════════════════════════════════════════
    // 정상 세포주 (Normal Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'hek293',
      name: 'HEK293',
      scientificName: 'Homo sapiens Embryonic Kidney',
      doublingTimeHours: 20.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'MEM + 10% FBS'],
      description: '인간 배아 신장 유래. 단백질 발현 연구에 사용.',
      category: '정상세포주',
    ),
    CellType(
      id: 'hek293t',
      name: 'HEK293T',
      scientificName: 'Homo sapiens Embryonic Kidney (SV40 T)',
      doublingTimeHours: 18.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: 'HEK293에 SV40 T항원 도입. 렌티바이러스 생산.',
      category: '정상세포주',
    ),
    CellType(
      id: 'huvec',
      name: 'HUVEC',
      scientificName: 'Human Umbilical Vein Endothelial Cell',
      doublingTimeHours: 24.0,
      medium: 'EGM-2 + 2% FBS',
      acceptableMediums: ['EGM-2 + 2% FBS', 'M199 + 20% FBS + EC growth supplement'],
      description: '인간 제대혈 내피세포. 혈관 연구에 사용.',
      category: '정상세포주',
    ),
    CellType(
      id: 'hmvec',
      name: 'HMVEC',
      scientificName: 'Human Microvascular Endothelial Cell',
      doublingTimeHours: 28.0,
      medium: 'EGM-2 MV + 5% FBS',
      acceptableMediums: ['EGM-2 MV + 5% FBS'],
      description: '인간 미세혈관 내피세포. 미세혈관 연구.',
      category: '정상세포주',
    ),
    CellType(
      id: 'hdfc',
      name: 'HDFC',
      scientificName: 'Human Dermal Fibroblast',
      doublingTimeHours: 36.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'DMEM + 15% FBS', 'FGM-2'],
      description: '인간 진피 섬유아세포. 피부 재생 연구.',
      category: '정상세포주',
    ),
    CellType(
      id: 'hs68',
      name: 'Hs68',
      scientificName: 'Homo sapiens Foreskin Fibroblast',
      doublingTimeHours: 36.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '인간 포피 섬유아세포. 노화 연구에 사용.',
      category: '정상세포주',
    ),
    CellType(
      id: 'wi38',
      name: 'WI-38',
      scientificName: 'Homo sapiens Lung Fibroblast',
      doublingTimeHours: 48.0,
      medium: 'MEM + 10% FBS',
      acceptableMediums: ['MEM + 10% FBS', 'DMEM + 10% FBS'],
      description: '인간 폐 섬유아세포 (이배체). 바이러스 연구.',
      category: '정상세포주',
    ),
    CellType(
      id: 'mrcs',
      name: 'MRC-5',
      scientificName: 'Homo sapiens Lung Fibroblast',
      doublingTimeHours: 40.0,
      medium: 'MEM + 10% FBS',
      acceptableMediums: ['MEM + 10% FBS'],
      description: '인간 폐 이배체 섬유아세포. 백신 생산.',
      category: '정상세포주',
    ),
    CellType(
      id: 'rpte',
      name: 'RPTEC',
      scientificName: 'Human Renal Proximal Tubule Epithelial Cell',
      doublingTimeHours: 48.0,
      medium: 'REBM + SingleQuots',
      acceptableMediums: ['REBM + SingleQuots', 'DMEM/F12 + ITS'],
      description: '신장 근위 세뇨관 상피세포. 신독성 연구.',
      category: '정상세포주',
    ),
    CellType(
      id: 'nhbe',
      name: 'NHBE',
      scientificName: 'Normal Human Bronchial Epithelial Cell',
      doublingTimeHours: 36.0,
      medium: 'BEGM + SingleQuots',
      acceptableMediums: ['BEGM + SingleQuots'],
      description: '정상 인간 기관지 상피세포.',
      category: '정상세포주',
    ),
    CellType(
      id: 'nhek',
      name: 'NHEK',
      scientificName: 'Normal Human Epidermal Keratinocyte',
      doublingTimeHours: 24.0,
      medium: 'KGM-Gold',
      acceptableMediums: ['KGM-Gold', 'EpiLife + HKGS'],
      description: '정상 인간 표피 각질형성세포.',
      category: '정상세포주',
    ),

    // ══════════════════════════════════════════
    // 동물 세포주 (Animal Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'cho',
      name: 'CHO',
      scientificName: 'Chinese Hamster Ovary',
      doublingTimeHours: 13.0,
      medium: 'Ham\'s F-12 + 10% FBS',
      acceptableMediums: ['Ham\'s F-12 + 10% FBS', 'DMEM/F12 + 10% FBS', 'CD CHO (SFM)'],
      description: '중국 햄스터 난소. 바이오의약품 생산의 표준.',
      category: '동물세포주',
    ),
    CellType(
      id: 'cho_k1',
      name: 'CHO-K1',
      scientificName: 'Chinese Hamster Ovary K1',
      doublingTimeHours: 12.0,
      medium: 'Ham\'s F-12 + 10% FBS',
      acceptableMediums: ['Ham\'s F-12 + 10% FBS', 'DMEM/F12 + 10% FBS'],
      description: 'CHO 아클론. 형질전환 단백질 생산.',
      category: '동물세포주',
    ),
    CellType(
      id: 'cos7',
      name: 'COS-7',
      scientificName: 'African Green Monkey Kidney',
      doublingTimeHours: 24.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '아프리카 녹색 원숭이 신장. 일시적 발현.',
      category: '동물세포주',
    ),
    CellType(
      id: 'vero',
      name: 'Vero',
      scientificName: 'African Green Monkey Kidney Epithelial',
      doublingTimeHours: 22.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'MEM + 5% FBS'],
      description: '바이러스 백신 생산에 널리 사용.',
      category: '동물세포주',
    ),
    CellType(
      id: '3t3',
      name: 'NIH 3T3',
      scientificName: 'Mus musculus Embryonic Fibroblast',
      doublingTimeHours: 20.0,
      medium: 'DMEM + 10% CS',
      acceptableMediums: ['DMEM + 10% CS', 'DMEM + 10% FBS'],
      description: '마우스 배아 섬유아세포주. 신호전달 연구.',
      category: '동물세포주',
    ),
    CellType(
      id: 'raw264',
      name: 'RAW264.7',
      scientificName: 'Mus musculus Macrophage',
      doublingTimeHours: 16.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '마우스 대식세포주. 면역학 연구에 사용.',
      category: '동물세포주',
    ),
    CellType(
      id: 'hepa1c1c7',
      name: 'Hepa1c1c7',
      scientificName: 'Mus musculus Hepatocellular Carcinoma',
      doublingTimeHours: 16.0,
      medium: 'α-MEM + 10% FBS',
      acceptableMediums: ['α-MEM + 10% FBS'],
      description: '마우스 간암 세포주. 간 독성 연구.',
      category: '동물세포주',
    ),
    CellType(
      id: 'sf9',
      name: 'Sf9',
      scientificName: 'Spodoptera frugiperda Ovarian',
      doublingTimeHours: 18.0,
      medium: 'Sf-900 III SFM',
      acceptableMediums: ['Sf-900 III SFM', 'Grace\'s Insect Medium + 10% FBS'],
      description: '곤충 세포주. 바큘로바이러스 발현 시스템.',
      category: '동물세포주',
      optimalTemp: 27.0,
      optimalPH: 6.2,
      co2Percent: 0.0,
    ),
    CellType(
      id: 'mef',
      name: 'MEF',
      scientificName: 'Mus musculus Embryonic Fibroblast',
      doublingTimeHours: 24.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '마우스 배아 섬유아세포. iPSC 연구 지지세포.',
      category: '동물세포주',
    ),
    CellType(
      id: 'l929',
      name: 'L929',
      scientificName: 'Mus musculus Subcutaneous Fibroblast',
      doublingTimeHours: 20.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS', 'DMEM + 10% FBS'],
      description: '마우스 피하 섬유아세포주. 생체적합성 시험.',
      category: '동물세포주',
    ),
    CellType(
      id: 'balb3t3',
      name: 'BALB/c 3T3',
      scientificName: 'Mus musculus Embryonic Fibroblast',
      doublingTimeHours: 22.0,
      medium: 'DMEM + 10% CS',
      acceptableMediums: ['DMEM + 10% CS', 'DMEM + 10% FBS'],
      description: 'BALB/c 마우스 유래. 형질전환 연구.',
      category: '동물세포주',
    ),

    // ══════════════════════════════════════════
    // 면역 세포주 (Immune Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'jurkat',
      name: 'Jurkat',
      scientificName: 'Homo sapiens T-cell Leukemia',
      doublingTimeHours: 24.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: 'T세포 백혈병 유래. 면역학 연구에 사용.',
      category: '면역세포주',
    ),
    CellType(
      id: 'k562',
      name: 'K-562',
      scientificName: 'Homo sapiens Chronic Myelogenous Leukemia',
      doublingTimeHours: 20.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '만성 골수성 백혈병. NK세포 연구에 사용.',
      category: '면역세포주',
    ),
    CellType(
      id: 'thp1',
      name: 'THP-1',
      scientificName: 'Homo sapiens Monocytic Leukemia',
      doublingTimeHours: 40.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '단핵구 백혈병. 염증 반응 연구.',
      category: '면역세포주',
    ),
    CellType(
      id: 'ramos',
      name: 'Ramos',
      scientificName: 'Homo sapiens B-cell Lymphoma',
      doublingTimeHours: 24.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: 'B세포 림프종 세포주.',
      category: '면역세포주',
    ),
    CellType(
      id: 'molt4',
      name: 'MOLT-4',
      scientificName: 'Homo sapiens T-cell Acute Lymphoblastic Leukemia',
      doublingTimeHours: 28.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: 'T세포 급성 림프모구 백혈병.',
      category: '면역세포주',
    ),
    CellType(
      id: 'hl60',
      name: 'HL-60',
      scientificName: 'Homo sapiens Acute Promyelocytic Leukemia',
      doublingTimeHours: 36.0,
      medium: 'RPMI-1640 + 20% FBS',
      acceptableMediums: ['RPMI-1640 + 20% FBS', 'IMDM + 20% FBS'],
      description: '급성 전골수구성 백혈병.',
      category: '면역세포주',
    ),
    CellType(
      id: 'u937',
      name: 'U-937',
      scientificName: 'Homo sapiens Monocytic Histiocytic Lymphoma',
      doublingTimeHours: 30.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '단핵구성 조직구성 림프종. 분화 연구.',
      category: '면역세포주',
    ),
    CellType(
      id: 'daudi',
      name: 'Daudi',
      scientificName: 'Homo sapiens B-cell Lymphoma (Burkitt)',
      doublingTimeHours: 26.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '버킷 림프종 B세포주. 인터페론 연구.',
      category: '면역세포주',
    ),

    // ══════════════════════════════════════════
    // 신경 세포주 (Neural Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'sh_sy5y',
      name: 'SH-SY5Y',
      scientificName: 'Homo sapiens Neuroblastoma',
      doublingTimeHours: 48.0,
      medium: 'DMEM/F12 (1:1) + 10% FBS',
      acceptableMediums: ['DMEM/F12 (1:1) + 10% FBS', 'DMEM + 10% FBS'],
      description: '신경모세포종 유래. 파킨슨병 연구에 사용.',
      category: '신경세포주',
    ),
    CellType(
      id: 'neuro2a',
      name: 'Neuro-2a',
      scientificName: 'Mus musculus Neuroblastoma',
      doublingTimeHours: 20.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '마우스 신경모세포종. 신경 분화 연구.',
      category: '신경세포주',
    ),
    CellType(
      id: 'pc12',
      name: 'PC12',
      scientificName: 'Rattus norvegicus Pheochromocytoma',
      doublingTimeHours: 48.0,
      medium: 'RPMI-1640 + 10% HS + 5% FBS',
      acceptableMediums: ['RPMI-1640 + 10% HS + 5% FBS'],
      description: '쥐 부신수질 종양. NGF 반응 연구.',
      category: '신경세포주',
    ),
    CellType(
      id: 'u251',
      name: 'U-251 MG',
      scientificName: 'Homo sapiens Glioblastoma',
      doublingTimeHours: 44.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'MEM + 10% FBS'],
      description: '교모세포종 세포주. 뇌종양 연구.',
      category: '신경세포주',
    ),
    CellType(
      id: 'ln229',
      name: 'LN-229',
      scientificName: 'Homo sapiens Glioblastoma',
      doublingTimeHours: 36.0,
      medium: 'DMEM + 5% FBS',
      acceptableMediums: ['DMEM + 5% FBS', 'DMEM + 10% FBS'],
      description: '교모세포종. PTEN 돌연변이 연구.',
      category: '신경세포주',
    ),

    // ══════════════════════════════════════════
    // 간 세포주 (Hepatic Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'hepg2',
      name: 'HepG2',
      scientificName: 'Homo sapiens Hepatocellular Carcinoma',
      doublingTimeHours: 48.0,
      medium: 'MEM + 10% FBS',
      acceptableMediums: ['MEM + 10% FBS', 'DMEM + 10% FBS'],
      description: '간암 유래. 약물 대사 연구에 사용.',
      category: '간세포주',
    ),
    CellType(
      id: 'huh7',
      name: 'Huh-7',
      scientificName: 'Homo sapiens Hepatocellular Carcinoma',
      doublingTimeHours: 36.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '간암 유래. B/C형 간염 연구에 사용.',
      category: '간세포주',
    ),
    CellType(
      id: 'hepg2_2b7',
      name: 'HepaRG',
      scientificName: 'Homo sapiens Hepatocellular Carcinoma',
      doublingTimeHours: 60.0,
      medium: 'William\'s E + GlutaMAX + Hydrocortisone + Insulin',
      acceptableMediums: ['William\'s E + GlutaMAX + Hydrocortisone + Insulin'],
      description: '간세포 기능 보유. CYP450 발현 연구.',
      category: '간세포주',
    ),
    CellType(
      id: 'fl83b',
      name: 'FL83B',
      scientificName: 'Mus musculus Hepatocyte',
      doublingTimeHours: 32.0,
      medium: 'Ham\'s F-12 + 10% FBS',
      acceptableMediums: ['Ham\'s F-12 + 10% FBS'],
      description: '마우스 간세포주. 간 대사 연구.',
      category: '간세포주',
    ),

    // ══════════════════════════════════════════
    // 심장/근육 세포주 (Cardiac/Muscle)
    // ══════════════════════════════════════════
    CellType(
      id: 'h9c2',
      name: 'H9c2',
      scientificName: 'Rattus norvegicus Cardiomyoblast',
      doublingTimeHours: 24.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '쥐 심근모세포. 심장 독성 연구.',
      category: '심장/근육세포주',
    ),
    CellType(
      id: 'c2c12',
      name: 'C2C12',
      scientificName: 'Mus musculus Myoblast',
      doublingTimeHours: 16.0,
      medium: 'DMEM + 20% FBS',
      acceptableMediums: ['DMEM + 20% FBS'],
      description: '마우스 근육모세포. 근육 분화 연구.',
      category: '심장/근육세포주',
    ),
    CellType(
      id: 'hl1',
      name: 'HL-1',
      scientificName: 'Mus musculus Atrial Cardiomyocyte',
      doublingTimeHours: 28.0,
      medium: 'Claycomb Medium + 10% FBS + NE + Insulin',
      acceptableMediums: ['Claycomb Medium + 10% FBS + NE + Insulin'],
      description: '마우스 심방 심근세포. 수축 기능 보유.',
      category: '심장/근육세포주',
    ),

    // ══════════════════════════════════════════
    // 골/연골 세포주 (Bone/Cartilage)
    // ══════════════════════════════════════════
    CellType(
      id: 'mg63',
      name: 'MG-63',
      scientificName: 'Homo sapiens Osteosarcoma',
      doublingTimeHours: 30.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'MEM + 10% FBS'],
      description: '골육종 유래. 골 재생 연구.',
      category: '골/연골세포주',
    ),
    CellType(
      id: 'saos2',
      name: 'Saos-2',
      scientificName: 'Homo sapiens Osteosarcoma',
      doublingTimeHours: 48.0,
      medium: 'McCoy\'s 5A + 15% FBS',
      acceptableMediums: ['McCoy\'s 5A + 15% FBS'],
      description: '골육종 유래. p53 연구에 사용.',
      category: '골/연골세포주',
    ),
    CellType(
      id: 'tc28a2',
      name: 'TC28a2',
      scientificName: 'Homo sapiens Chondrocyte',
      doublingTimeHours: 40.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'DMEM + 10% FBS + ITS'],
      description: '인간 연골세포. 골관절염 연구.',
      category: '골/연골세포주',
    ),
    CellType(
      id: 'sw1353',
      name: 'SW1353',
      scientificName: 'Homo sapiens Chondrosarcoma',
      doublingTimeHours: 44.0,
      medium: 'L-15 + 10% FBS',
      acceptableMediums: ['L-15 + 10% FBS'],
      description: '연골육종 세포주. 연골 기질 연구.',
      category: '골/연골세포주',
      co2Percent: 0.0,
    ),

    // ══════════════════════════════════════════
    // 신장 세포주 (Renal Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'hk2',
      name: 'HK-2',
      scientificName: 'Homo sapiens Proximal Tubular Kidney',
      doublingTimeHours: 48.0,
      medium: 'DMEM/F12 + 10% FBS',
      acceptableMediums: ['DMEM/F12 + 10% FBS', 'K-SFM + EGF + BPE'],
      description: '인간 신장 근위 세뇨관 세포주.',
      category: '신장세포주',
    ),
    CellType(
      id: 'mdck',
      name: 'MDCK',
      scientificName: 'Canis lupus familiaris Kidney',
      doublingTimeHours: 22.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'MEM + 10% FBS'],
      description: '개 신장 상피 세포주. 극성 연구에 사용.',
      category: '신장세포주',
    ),
    CellType(
      id: 'achn',
      name: 'ACHN',
      scientificName: 'Homo sapiens Renal Cell Adenocarcinoma',
      doublingTimeHours: 38.0,
      medium: 'MEM + 10% FBS',
      acceptableMediums: ['MEM + 10% FBS'],
      description: '신장암 세포주.',
      category: '신장세포주',
    ),

    // ══════════════════════════════════════════
    // 폐 세포주 (Pulmonary Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'beas2b',
      name: 'BEAS-2B',
      scientificName: 'Homo sapiens Bronchial Epithelial',
      doublingTimeHours: 24.0,
      medium: 'LHC-9 Medium',
      acceptableMediums: ['LHC-9 Medium', 'BEGM + SingleQuots'],
      description: '인간 기관지 상피 세포주.',
      category: '폐세포주',
    ),
    CellType(
      id: 'calu3',
      name: 'Calu-3',
      scientificName: 'Homo sapiens Lung Adenocarcinoma',
      doublingTimeHours: 48.0,
      medium: 'MEM + 10% FBS',
      acceptableMediums: ['MEM + 10% FBS', 'DMEM + 10% FBS'],
      description: '폐 선암 세포주. 폐 장벽 연구.',
      category: '폐세포주',
    ),
    CellType(
      id: 'nci_h460',
      name: 'NCI-H460',
      scientificName: 'Homo sapiens Large Cell Lung Carcinoma',
      doublingTimeHours: 18.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '대세포 폐암 세포주.',
      category: '폐세포주',
    ),

    // ══════════════════════════════════════════
    // 피부 세포주 (Skin Cell Lines)
    // ══════════════════════════════════════════
    CellType(
      id: 'hacat',
      name: 'HaCaT',
      scientificName: 'Homo sapiens Keratinocyte',
      doublingTimeHours: 24.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS', 'KGM-Gold'],
      description: '인간 각질형성세포. 피부 연구에 사용.',
      category: '피부세포주',
    ),
    CellType(
      id: 'sk_mel_28',
      name: 'SK-MEL-28',
      scientificName: 'Homo sapiens Melanoma',
      doublingTimeHours: 30.0,
      medium: 'MEM + 10% FBS',
      acceptableMediums: ['MEM + 10% FBS', 'DMEM + 10% FBS'],
      description: '흑색종 세포주. 항암제 연구.',
      category: '피부세포주',
    ),
    CellType(
      id: 'a375',
      name: 'A375',
      scientificName: 'Homo sapiens Melanoma',
      doublingTimeHours: 24.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '흑색종 세포주. BRAF V600E 돌연변이.',
      category: '피부세포주',
    ),

    // ══════════════════════════════════════════
    // 기타 / 특수 세포주
    // ══════════════════════════════════════════
    CellType(
      id: 'hpde',
      name: 'HPDE',
      scientificName: 'Human Pancreatic Ductal Epithelial Cell',
      doublingTimeHours: 40.0,
      medium: 'Keratinocyte-SFM + EGF + BPE',
      acceptableMediums: ['Keratinocyte-SFM + EGF + BPE'],
      description: '인간 췌관 상피세포. 췌장암 비교 연구.',
      category: '기타세포주',
    ),
    CellType(
      id: 'ht1197',
      name: 'HT-1197',
      scientificName: 'Homo sapiens Urinary Bladder Carcinoma',
      doublingTimeHours: 38.0,
      medium: 'MEM + 10% FBS',
      acceptableMediums: ['MEM + 10% FBS'],
      description: '방광암 세포주.',
      category: '기타세포주',
    ),
    CellType(
      id: 'rt4',
      name: 'RT4',
      scientificName: 'Homo sapiens Urinary Bladder Transitional Papilloma',
      doublingTimeHours: 26.0,
      medium: 'McCoy\'s 5A + 10% FBS',
      acceptableMediums: ['McCoy\'s 5A + 10% FBS'],
      description: '방광 이행세포 유두종.',
      category: '기타세포주',
    ),
    CellType(
      id: 'eca109',
      name: 'Eca-109',
      scientificName: 'Homo sapiens Esophageal Carcinoma',
      doublingTimeHours: 30.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '식도암 세포주.',
      category: '기타세포주',
    ),
    CellType(
      id: 'lovo',
      name: 'LoVo',
      scientificName: 'Homo sapiens Colorectal Adenocarcinoma',
      doublingTimeHours: 36.0,
      medium: 'Ham\'s F-12 + 10% FBS',
      acceptableMediums: ['Ham\'s F-12 + 10% FBS'],
      description: '대장선암 세포주. 약물 내성 연구.',
      category: '기타세포주',
    ),
    CellType(
      id: 'ht22',
      name: 'HT22',
      scientificName: 'Mus musculus Hippocampal Neuron',
      doublingTimeHours: 24.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '마우스 해마 신경세포. 산화 스트레스 연구.',
      category: '기타세포주',
    ),
    CellType(
      id: 'rin_m5f',
      name: 'RIN-m5F',
      scientificName: 'Rattus norvegicus Insulinoma',
      doublingTimeHours: 40.0,
      medium: 'RPMI-1640 + 10% FBS',
      acceptableMediums: ['RPMI-1640 + 10% FBS'],
      description: '쥐 인슐린종. 췌장 β세포 연구.',
      category: '기타세포주',
    ),
    CellType(
      id: 'min6',
      name: 'MIN6',
      scientificName: 'Mus musculus Insulinoma',
      doublingTimeHours: 48.0,
      medium: 'DMEM + 15% FBS + β-ME',
      acceptableMediums: ['DMEM + 15% FBS + β-ME'],
      description: '마우스 췌장 β세포주. 인슐린 분비 연구.',
      category: '기타세포주',
    ),
    CellType(
      id: 'a431',
      name: 'A431',
      scientificName: 'Homo sapiens Epidermoid Carcinoma',
      doublingTimeHours: 22.0,
      medium: 'DMEM + 10% FBS',
      acceptableMediums: ['DMEM + 10% FBS'],
      description: '표피양 암종. EGFR 과발현 세포주.',
      category: '기타세포주',
    ),
    CellType(
      id: 'hs578t',
      name: 'Hs578T',
      scientificName: 'Homo sapiens Breast Carcinosarcoma',
      doublingTimeHours: 34.0,
      medium: 'DMEM + 10% FBS + Insulin',
      acceptableMediums: ['DMEM + 10% FBS + Insulin'],
      description: '유방 암육종 세포주. 침윤성 연구.',
      category: '기타세포주',
    ),
  ];

  static List<String> get allMediums {
    final Set<String> mediums = {};
    for (final cell in cells) {
      mediums.addAll(cell.acceptableMediums);
    }
    return mediums.toList()..sort();
  }

  static List<String> get categories {
    final Set<String> cats = {};
    for (final cell in cells) {
      cats.add(cell.category);
    }
    return cats.toList()..sort();
  }

  static CellType? findById(String id) {
    try {
      return cells.firstWhere((c) => c.id == id);
    } catch (_) {
      return null;
    }
  }
}
